location: UK South
enableUkNhs: True 
service:
  dependencies:
    workspace: Core-Test-Ws
securityContacts:
  primary:
    email: security.test1@cloudmarque.com                # First set of contact details can have an email and phone set.
    phone: +447911111111
  additionalEmails: [
    security.test2@cloudmarque.com,
    security.test3@cloudmarque.com
  ]